# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy source files
COPY . .

# Build the project
RUN npm run build

# Expose any necessary port (if applicable)
# For MCP, typically uses stdio. If needed, uncomment the next line and adjust port
# EXPOSE 3000

# Command to run the MCP server
CMD ["node", "dist/index.js"]
